### PR TITLE
Update OneFichierCom.php

### PR DESCRIPTION
**Pull request by babasss**
Add function GenerateCurl (which missed) and fixing Array options value

### CODE REVIEW

**Comment by sousouille** [comment]
Thx for your fix. I confirm it works !

**Comment by yaajxaab** [comment]
Hi,
I'm a Mac user, is it possible to get the file in .host, please ?

French guy.

**Comment by babasss** [comment]
Hello,
I post it on nas-forum : https://www.nas-forum.com/forum/topic/37274-fichier-host-1fichier-host-file-1fichier/?do=findComment&comment=1319377177

**Comment by Arnaudvs987** [comment]
Hello guys,

Thank you for your many contributions. Sadly for me, the 3.2 still doesn't work on my very old NAS (DS109). I can't upgrade higher than the DSM 4.2. Can it be the cause ? Was working fine with the 2.9 then it suddenly stopped. Could you look into it if it's not too much to ask, please ?

**Comment by babasss** [comment]
I recommend you to test with 3.2.2. You can found the source here or download the .host on https://www.nas-forum.com/forum/topic/37274-fichier-host-1fichier-host-file-1fichier/?do=findComment&comment=1319377397

**Comment by Arnaudvs987** [comment]
@babasss 
Thanks. I've tried it immediately and it's still the same, nothing happens but noticed something this time. When I put my premium account and test it, it says ok. Then I leave and I come back, the login and password fields are empty again. So something is missing. I know it happened in a previous version but I don't know what was done to solve that. Thanks anyway for your many efforts !
Cheers !

**Pull request merged**
